#------------WEB监听端口------------
server:
  port: 8090
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 3600s

#------------JDBC配置------------
# 驱动配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #连接池的配置信息
    initialSize: 100
    minIdle: 500
    maxActive: 500
    maxWait: 600000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

#------------Redis配置------------
redis:
  #单机主机
  hostName: 127.0.0.1
  #单机端口号
  port: 6379
  #集群
#  cluster:
#    nodes: 10.10.50.140:9000,10.10.50.141:9000,10.10.50.142:9000
#    max-redirects: 6
  #如果有密码
  password:
  #  password:
  #数据库(默认0)
  database: 0
  #客户端超时时间单位是毫秒 默认是2000
  timeout: 10000
  #最大空闲数
  maxIdle: 300
  #连接池的最大数据库连接数。设为0表示无限制,如果是jedis 2.4以后用maxTotal
  #maxActive: 600
  #控制一个pool可分配多少个jedis实例,用来替换上面的maxActive,如果是jedis2.4以后用该属性
  maxTotal: 1000
  #最大建立连接等待时间。如果超过此时间将接到异常。设为-1表示无限制。
  maxWaitMillis: 1000
  #连接的最小空闲时间 默认1800000毫秒(30分钟)
  minEvictableIdleTimeMillis: 300000
  #每次释放连接的最大数目,默认3
  numTestsPerEvictionRun: 1024
  #逐出扫描的时间间隔(毫秒) 如果为负数,则不运行逐出线程, 默认-1
  timeBetweenEvictionRunsMillis: 30000
  #是否在从池中取出连接前进行检验,如果检验失败,则从池中去除连接并尝试取出另一个
  testOnBorrow: true
  #在空闲时检查有效性, 默认false
  testWhileIdle: true


rocketmq:
  consumer:
    # RocketMQ的请求地址
    namesrvAddr: 127.0.0.1:9876
    # 发送同一类消息的设置为同一个group，保证唯一,默认不需要设置，rocketmq会使用ip@pid(pid代表jvm名字)作为唯一标示
    groupName: test-demo
    #如果需要同一个jvm中不同的producer往不同的mq集群发送消息，需要设置不同的instanceName
    instanceName: consumer.demo
  producer:
    #发送消息超时时间
    sendMsgTimeout: 10000
    #maxMessageSize最大消息限制
    maxMessageSize: 999999999
    #消息大小超出配置对消息压缩
    compressOver: 40000
  topic: test-demo
  # 不配置为订阅全部tag,多个行业用 "||" 分隔, 如："0||1||2"
  tag: "111"



##druid管理
druid:
  loginUsername: DOiB+hq/QmiZePNvhlk9ig==
  loginPassword: RIETaw/OueFdiwdezO8mic4fmEXV+8mC

