#------------WEB监听端口------------
server:
  port: 8091
  tomcat:
    uri-encoding: utf-8
  servlet:
    session:
      timeout: 3600s

#------------JDBC配置------------
# 驱动配置信息
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8
    username: root
    password: 123456
    #连接池的配置信息
    initialSize: 100
    minIdle: 500
    maxActive: 500
    maxWait: 600000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: SELECT 1 FROM DUAL
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    filters: stat,wall,log4j
    connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=500
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss



##druid管理
druid:
  loginUsername: DOiB+hq/QmiZePNvhlk9ig==
  loginPassword: RIETaw/OueFdiwdezO8mic4fmEXV+8mC

